# Generated by Django 3.0.6 on 2020-05-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitem',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipeitem',
            old_name='date',
            new_name='time',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
